export const quotes: [string, string][] = [
  ["Carlijn", "Zullen we een frisse neus halen in het rokershok?"],
  ["Cato", "*stil in een hoekje* Tyfus kankerpuzzel"],
  ["Cato", "Mag ik een fles bubbels? "],
  [
    "Cato, Floris",
    "Cato: ‘Ik wil mijn appel compote bakje niet vingeren’ Jeffrey: ‘waarom niet?’ Cato: ‘omdat het voor babies bedoeld is’",
  ],
  [
    "Cato, Floris",
    "Cato: ‘Ik wil mijn appel compote bakje niet vingeren’ Jeffrey: ‘waarom niet?’ Cato: ‘omdat het voor babies bedoeld is’",
  ],
  [
    "Cato, Floris",
    "Cato: ‘Ik wil mijn appel compote bakje niet vingeren’ Jeffrey: ‘waarom niet?’ Cato: ‘omdat het voor babies bedoeld is’",
  ],
  ["Darell", "Ik wilde gewoon iedereen neuken"],
  ["Darrel", "Kan ik op deze neukmachine zitten? Dat ie me in mijn aars pakt."],
  ["Darrell", "ik wil een zwarte, homoseksuele downie. Nu."],
  [
    "Darrell",
    "ik wil best een downie aannemen als we daar voor gratis bier krijgen",
  ],
  ["Darrell", "Waar is die kenker Karel..."],
  [
    "Darrell",
    "Als je voor Kruidvat eigen merk gaat stop je je penis gewoon in een SOA",
  ],
  [
    "Darrell",
    "Er komt bij gebrek aan betere kleuren een geel kindje in het spel",
  ],
  ["Darrell", "Hij was lekkerder toen ie kouder was"],
  ["Darrell", "Mensen fixen, dat is helemaal niet zo moeilijk"],
  ["Darrell", "Mijn penis is 1 penis lang, maar 3 penissen dik"],
  ["Darrell", "DARRELL HEEFT EEN GROTE PIEMEL HEEEEUUUUJJ"],
  [
    "Darrell",
    "Als mensen katten waren, zouden we allemaal drugsverslaafde zijn",
  ],
  ["Darrell", "Ik heb nu meer een tampon dan een penis."],
  ["Darrell", "Ik heb eigenlijk liever een Yorinfer dan Thierry"],
  [
    "Darrell",
    "Die koeien lijken wel op paarden, dus dan kunnen we die aftrekken.",
  ],
  ["Darrell", "Ik heb enorm veel respect voor fietsendieven."],
  ["Darrell", "Carlijn, ik zou best naast je durven slapen."],
  [
    "Darrell",
    "Stel ik ga samenwonen met Linda, krijgt ze sowieso niet meer dan de wc en de keuken.",
  ],
  [
    "Darrell",
    'Terwijl hij een stok op en neer ragt: "Dit moet je met kindernekjes doen!"',
  ],
  ["Darrell", "Telt het als een trio als ze zwanger is?"],
  ["Darrell", "Flip is lekker (Flip was er niet bij) "],
  ["Darrell", "Flip is wel serieus goeie (Flip was er niet bij) "],
  ["Darrell", "Kut, dan heb ik seks gehad met mijn oma"],
  ["Darrell", "We gaan vanaf morgen allemaal sporten!!"],
  [
    "Darrell ",
    "Dat heb je toch ook wel eens in bed, dat je niet omhoog kan komen?",
  ],
  ["Darrell ", "Ik was zeventien voor een half jaar."],
  ["Darrell ", "'Vo voor de NSB'ers!"],
  [
    "Darrell ",
    "Als ik krullende dingen zou willen eten zou ik wel Jeffrey's schaamhaar eten.",
  ],
  [
    "Darrell - Cato",
    "Ja ijsberen zijn de meest aggressieve beren van allemaal - Maar hij is wit",
  ],
  [
    "Darrell - Heleen, Frank en Floris",
    '"Dus alle grote, zwarte mannen lijken op the rock?" - "Ja!"',
  ],
  [
    "Darrell, Jeffrey ",
    "Dat gaan we nu echt doen. Wat? Ons inschrijven bij de KVK. *droevig* Oh, ik dacht dat we naar de muur gingen.",
  ],
  ["Darrell, tegen Heleen", "Ah wat ben jij lelijk"],
  [
    "Flip, Jeffrey",
    '"Jij kan nu ook babies maken!", "Ja! Ik kan ook babies maken."',
  ],
  ["Floris", "I like tentacle porn"],
  [
    "Floris",
    "Mannenliefde is wel lekker hoor. Ja dat is wel lekker, heb ik vrijdag nog gekregen",
  ],
  ["Floris", "iK bEn Er MoRgEn SoWiEsO oM NeGeN UuR ~ KaReL"],
  ["Floris", 'Over tentakel-porno: "Lindsay, je hebt te weinig armen"'],
  ["Floris", "He we hebben helemaal geen neger in BAGGER! "],
  ["Floris", "Want ik had regelmatig seks met Joost"],
  ["Floris", "Ik ben 11 :)"],
  ["Floris", "Wat is Floris kut zeg haha"],
  ["Floris", "Ohh ik wil meer van Oliver"],
  [
    "Floris en Karel",
    '"Alles wordt nat hier" - "Is dat nieuw voor jou?" - *Lindsay moet lachen* - "Nou het is wel even geleden" - *Lindsay stopt met lachen*',
  ],
  ["Frank", "Hoe weet ik nou of ik een gender ben?"],
  ["Frank", "113 is not busy right now, so that's totally fine"],
  ["Frank", "Want ik heb een penis"],
  ["Frank", "Karel je hebt wel een dikke penis"],
  ["Frank", "Consent is laf"],
  [
    "Frank",
    "Hij is misschien niet intelligent, maar hij is tenminste wel blank.",
  ],
  ["Frank", "Alleen in het weekend. Net als pep."],
  ["Frank", "Er is altijd wel een andere jood die je plek in kan nemen"],
  ["Frank", "Ontgroenen is Agile as fuck"],
  ["Frank", "KOOP DRUGS VOOR ME *sensueel gekreun*"],
  ["Frank", "Ik ga gewoon een kind inhuren"],
  ["Frank", "Slavery, fuck yeah!"],
  ["Frank", "Why no SS, man?"],
  [
    "Frank",
    'Als ik één ding heb geleerd in Arnhem is het "vertrouw nooit een Koerd"',
  ],
  ["Frank", "Ik ben een byte"],
  ["Frank", '"Harassen" is mijn tweede naam'],
  ["Frank", "Ik wil geen zwarte jongen zijn in dat blanke huis"],
  ["Frank", "Doina is een demigod"],
  ["Frank", "Ik zie geen kleur, alleen zwart-wit. Arme Chinezen"],
  ["Frank", "Allah Akbar? — *Darrell steekt enthousiast zijn duim op*"],
  ["Frank", "Jazeker heb ik een 13-jarige versierd op Minecraft."],
  ["Frank", "Ik zou frequenter moeten roken"],
  [
    "Frank",
    "Ik wil best wel wat griptraining doen in de vagina van een zestienjarige",
  ],
  ["Frank", "Mag ik je kind likken? "],
  ["Frank", "Al-Qaeda zijn ook studenten, toch?"],
  ["Frank", "Grolsch is de enige die ik kapitalisme gun."],
  ["Frank", "Opzich, kinderslavernij is niet zo erg"],
  ["Frank, Carlijn ", "Nou, trekken! Kan ik!"],
  [
    "Frank, Darrell",
    '"Vrouwencondooms beschermen tegen ongewenste zwangerschap" - "kanker" ',
  ],
  [
    "Frank, Darrell",
    "Wanneer wordt iets seks? - Wanneer je je piemel er in steekt!",
  ],
  [
    "Frank, Karel, Floris",
    "Vind je dat oke Karel? - Ja, je hebt mijn consent. - Dat boeit ons toch niet",
  ],
  [
    "Heleen",
    "Probeer mij dan te versieren? Probeer mij in die positie te krijgen",
  ],
  ["Heleen", "Jeffrey houdt helemaal niet van sex!"],
  ["Heleen", "Ik ga niet in general trekken."],
  ["Heleen", "Oeeh! Andere gaatjes!"],
  ["Heleen", "Heb jij een krant? Dan maak ik 'm nat."],
  [
    "Heleen, Floris ",
    "Mag ik mijn hoofd op jouw been leggen? Ja, maar dan moet je het niet erg vinden als het wat plakkerig wordt.",
  ],
  ["Ilse", "Slaan mag alleen in bed"],
  [
    "Ilse",
    "Een school overhoop schieten doe je niet in je vrije tijd; dat is onder schooltijd.",
  ],
  ["Ilse", "Dus nu gaat het over wat zij aan haar lichaam heeft zitten."],
  ["Ilse", "Ik ben te wit om hier grappen over te maken."],
  ["Ilse", "KIJK MIJ IK HEB EEN DIKKE PENIS"],
  ["Ilse", "Maar 5 versnellingen, dat is echt iets voor je twééde auto"],
  ["Ilse", "hoera voor kromme penissen"],
  ["Ilse", "Ah shit, mijn avocado"],
  ["Ilse", "Ik heb geen penis, denk ik."],
  ["Jeffrey", "een consent-condoom is echt een matige uitvinding"],
  ["Jeffrey", 'Over lesbiennes: "Oh, die hebben toch geen standaarden meer"'],
  ["Jeffrey", "Ik ga het condoom denk ik niet dragen"],
  ["Jeffrey", "Heb je de TV überhaupt gevraáágd om consent?"],
  ["Jeffrey", "Nou dat wordt plakken"],
  ["Jeffrey", "Kinderen zijn onbreekbaar"],
  ["Jeffrey", "NeEeEe, ik wil niet legaal zijn Karel!"],
  ["Jeffrey", "Als het geen CO2 is, is het wel CO3"],
  ["Jeffrey", "jeej Police Brutality"],
  [
    "Jeffrey",
    "Zo, nu is het tijd voor Nazi's. Ik snap niet dat jullie daar zo moeilijk over doen.",
  ],
  ["Jeffrey", "Ik ben grotendeels racistisch tegen Duitsers"],
  [
    "Jeffrey",
    "Ja ik heb 1 2 3 4 sloeries gebruikt, want ik heb 1 2 3 4 sloeries in huis. En mijn sloeries ja die willen naar huis want ik heb 1 2 3 4 sloeries gebruikt",
  ],
  ["Jeffrey", "Onze penis hangt los."],
  ["Jeffrey", "(iemand pleegt zelfmoord op de tv) Ooh, ik vind dit zo laf!"],
  ["Jeffrey", "Een begroting is er om van af te wijken."],
  ["Jeffrey", "(heel blij) Gaan we Floris verkrachten?!"],
  ["Jeffrey", "I want to bang a midget so I can feel like a man."],
  ["Jeffrey", "Ik ben een schappelijke pimp, ik neem maar 25%"],
  [
    "Jeffrey",
    "Ik weet niet wat goede marges zijn voor pimps, maar dit lijkt me wel redelijk",
  ],
  ["Jeffrey", "Blanke mensen horen niet binnen de muren van een gevangenis"],
  ["Jeffrey", "Het maakt toch niet uit dat ze zeventien is?"],
  ["Jeffrey", "Van Mourik is er ook overheen gegaan."],
  ["Jeffrey", "Het is niet wurgen. =J"],
  ["Jeffrey", "Ik heb jou ook nog nooit anaal gepenetreerd."],
  ["Jeffrey", "Wat is dit voor zachte plek? Oh, het is niet zacht meer!"],
  ["Jeffrey", "Ik wil je wel verpimpen hoor, geen zorgen."],
  ["Jeffrey", "Ieder raam is een swastika."],
  ["Jeffrey", "Ze is jong en ze wil wat. Gevuld worden. Tot het randje."],
  ["Jeffrey", "Flevoland is vanaf nu een Christelijke ethnostaat."],
  ["Jeffrey", "We eten geel vandaag! *maniacaal gelach*"],
  ["Jeffrey", "Kinderen met depressie, dat is gezond."],
  ["Jeffrey", "Haal je tepels uit de tuin."],
  ["Jeffrey", "Joost, jij bent een verkrachter."],
  ["Jeffrey", "Maar het is niet woke, en dat is wat uitmaakt."],
  ["Jeffrey", "Meer hoeren, meer beter."],
  [
    "Jeffrey",
    "En waarom zijn wij koud? Zodat chicks tegen ons aan willen kruipen!",
  ],
  [
    "Jeffrey",
    "*peinzend* Waarom is hij op Bol.com goedkoper? Omdat hij zwart is?",
  ],
  [
    "Jeffrey",
    "Ik bedoel hoer in de positieve zin van het woord. (Over vrouwen met gekleurd haar)",
  ],
  [
    "Jeffrey",
    "Als jij sensueel tegen mij gaat doen, ga ik sensueel tegen jou doen, Karel",
  ],
  ["Jeffrey", "We gaan sletten kijken!"],
  ["Jeffrey", "Waarom mag je anderen niet spanken?"],
  [
    "Jeffrey",
    "Een Jodenster op hun borst projecteren; dat is toch de volgende stap? Ik zeg niet dat ik er voor ben, maar...",
  ],
  ["Jeffrey", "Ik heb nooit beweerd dat ik een man ben."],
  ["Jeffrey", "Als dode tetten je ding zijn... ik judge niet."],
  ["Jeffrey", "Lengte is geen probleem, als je de techniek maar beheerst."],
  ["Jeffrey", "Je moet blijven zuigen, anders gaat het fout."],
  [
    "Jeffrey",
    "*Frank geeft seksuele voorlichting* Oh hier ga ik even een notitie van maken!",
  ],
  ["Jeffrey ", "Ja, zolang dat geweten een bankrekening heet!"],
  [
    "Jeffrey ",
    "Ik kan geen MILF regelen. De vraag is hoe weet ik dat. Is het A. ervaring, of B. speculatie?",
  ],
  ["Jeffrey ", "Censuur is echt een goed idee."],
  ["Jeffrey ", "Nee, ik heb over het hele toilet gesprayed!"],
  [
    "Jeffrey ",
    "Kennelijk als je een deken in de wasmachine stopt wordt hij erg nat.",
  ],
  ["Jeffrey ", "Je kan uit zijn mond pissen!"],
  [
    "Jeffrey ",
    "Dan adopteer je ze gewoon als ze zeven zijn, en dat is beter want... euh... wat was mijn punt ook alweer?",
  ],
  ["Jeffrey ", "(enthousiast) Keta, lekker, hhhm!"],
  ["Jeffrey ", "Ik heb geen glimi (glijmiddel) nodig."],
  ["Jeffrey ", "Mijn server is gekleurd! Oh..."],
  ["Jeffrey ", "Ik weet hoeveel jij houdt van niet dingen aanduwen."],
  ["Jeffrey ", "Pas op met het slurfje."],
  ["Jeffrey ", 'Ik dacht: "Wow, unieke oksels!"'],
  [
    "Jeffrey tegen Floris",
    "Als jij blijft slikken, dan blijf ik in je mond spuiten",
  ],
  ["Jeffrey, Karel", '"Karie, zullen we een kitten nemen?" - "Nee."'],
  [
    "Jeffrey, Karel",
    "We moeten Ilse nog even vullen. - Ehh, zullen we dat gewoon aan mij overlaten?",
  ],
  [
    "Jeffrey, Karel",
    "Waarom is er altijd drama met die vrouwen? Wat was het laatste woord dat je zei. Vrouwen? Bingo!",
  ],
  ["Joost", "De truc is gewoon om zo diep mogelijk te pakken"],
  ["Joost", "Jeffrey, zet fucking communism uit."],
  ["Joost", "he, ze is 16, in de middeleeuwen was dat meerderjarig"],
  ["Joost", "Eindelijk, meerderjarige singles"],
  [
    "Joost",
    "Ik zei toch, ik krijg het altijd warm van die nerveuze BIT-meisjes",
  ],
  ["Joost", "Swaffelen is een werkwoord, dat moet je doen"],
  [
    "Joost",
    "Je onderschat hoe robuust kinderen zijn als je niet toegeeft dat ze een wond hebben",
  ],
  ["Joost", "Nee, ik heb liever een koud BIT-meisje"],
  ["Joost", "Ik hoor altijd dat ik structureel te hard stoot"],
  ["Joost", "Ik wilde nog wat met die handbalster doen"],
  ["Joost", "Dit is echt precies de juiste verhouding vocht en vulling"],
  ["Joost", "*Kreunt erg hard* MIJN PORTEFEUILLE IS ZO DIK!"],
  [
    "Joost",
    "Moeten wij eens naar Marokko gaan en daar hun banen innemen; hebben we nog beter weer ook.",
  ],
  [
    "Joost",
    "*over racisme* Tja, als je altijd de groep bent die wordt onderdrukt, moet je misschien eerst eens naar jezelf kijken",
  ],
  [
    "Joost",
    "We hebben romantiek nodig, dus halen we de consent weg, dan gaat alles sneller. ",
  ],
  ["Joost", "Dat het onethisch is, maakt het nog niet illegaal"],
  [
    "Joost",
    "Je moet wel salten, anders krijg je ✨🌈rainbow-tables🌈✨, en dat is fucking gay",
  ],
  ["Joost", "Zijn we niet allemaal op zoek naar die ene speciale dominatrix? "],
  ["Joost", "Ik maak gewoon misbruik van haar hormonen"],
  [
    "Joost",
    'Over mogelijke kleinkinderen: "Dus, ben je al een paar keer goed in haar kut klaargekomen?" 🍆💦',
  ],
  [
    "Joost",
    "Iets aan een zevenjarige die zó agressief aan het hip-thrusten is maakt mij zeer ongemakkelijk",
  ],
  ["Joost", "Naaldhakken én weeb-haar. DOMINEER MIJ"],
  ["Joost", "But look at that gamer ASS"],
  ["Joost", "Een vrouw van 30 met een sixpack, dat is not net wat ik zoek"],
  ["Joost", "Poooh, ik heb een kankerbanaan"],
  ["Joost", "Smegma komt van de natuur"],
  ["Joost", "*In roomblanke stem:* Haar poenie wil ik kaal"],
  [
    "Joost",
    "Zolang het niet van deze PC afkomt is het in ieder geval geen verspreiding van kinderporno",
  ],
  ["Joost", "Die van Heleen is nog pluiziger dan dat!"],
  ["Joost", "Kink shamen is mijn kink. IK WORD ZO HARD VAN DEZE VIDEO"],
  ["Joost", "Een dominante criminele goth girlfriend, that's the dream"],
  ["Joost", '*Over schaaracties* "Maar ik hoop er zo op" '],
  ["Joost", "Je vader is net lekker klaargekomen in mijn kut, kind"],
  ["Joost", "Fascisme is niet echt mijn ding, maar het is wel leuk"],
  ["Joost", '*Over seksuele ontwikkeling "Straks moet ik nog bijles krijgen" '],
  [
    "Joost",
    "Je bent alleen een échte vrouw als je 150 bent en 10 kilo weegt. Those Ethiopian beauty standards",
  ],
  ["Joost", "Give me your babies"],
  ["Joost", "Een hand naar voren; doe de onderwater nazi-groet"],
  ["Joost", "Ik vertrouw hun genitaliën niet"],
  ["Joost", "Dekolonisatie was op zich een goed ding, maar het is wel jammer."],
  ["Joost", "Ouchie-wowchie, ik kreeg een schwokkie wokkie~ uwu"],
  ["Joost", "Nee, dat DURF jij niet met je penis"],
  ["Joost", "Ik krijg een rage-boner van neo-liberalen"],
  ["Joost", "Nee Jeffrey, ik wil tieten vol zand"],
  ["Joost", "I don't need no pussy in my life"],
  ["Joost", "Dat is waar de magie gebeurt; de gehandicapten-badkamer"],
  [
    "Joost",
    "50.000m2 aan perceel, even uitrekenen. Hoeveel ben je dan ten alle tijden verwijderd van minderheden?",
  ],
  [
    "Joost",
    "She's got the bottom, she's got the curls; she is my kind of girl 😏",
  ],
  ["Joost", "Pipe thrust forces, daar ben ik wel bekend mee 😏"],
  ["Joost", "Dan kan je tenminste zonder luier naar de dimibo"],
  ["Joost", "Het is voor haar eigen bestwil, consent be damned!"],
  ["Joost", "Thicc but spreadable, just how I like 'em"],
  ["Joost", "Ik wil mijn kut altijd minimaal"],
  ["Joost", "Waar schaarste heerst, groeit het kapitalisme"],
  ["Joost", "Kerken zijn makkelijker te vinden dan Italianen"],
  ["Joost", "Lana heeft het vast niet door dat we hier lopen te 69-en"],
  [
    "Joost",
    "Ik kan ze nooit uit elkaar halen tot ze zich omdraaien (over vrouwen)",
  ],
  [
    "Joost en Jeffrey",
    "Hopefully we've committed genocide. - I like genocide. ",
  ],
  ["Joost, Jeffrey", "Verkracht. Wat? Verkracht. Mooi."],
  [
    "Joost, Jeffrey",
    "Dat kwam erg van pas toen ze de lokale bevolking moesten onderdrukken. Oh, je leert elke dag wat nieuws.",
  ],
  [
    "Joost, Jeffrey",
    "Jij hebt geen Haags kookboek. En daarom is je penis krom!",
  ],
  ["Joost, Jeffrey", "Sex. Wat? Sex"],
  [
    "Joost, Jeffrey",
    "Dus jij gaat allemaal koenkies fixen met de site? Ja, alle vrouwelijke sjaarsen!",
  ],
  ["Joost, Karel", '"Wij gaan aan segregatie doen." — "Mooi!"'],
  ["Karel", "Ik laat me niet cucken door een twaars"],
  [
    "Karel",
    '"Hoe heet deze sheet ook alweer?" - "DE BAGGER QUOTELIJST MET ALLEMAAL QUOTES DIE NET KIELE-KIELE WEL OF NIET MAATSCHAPPELIJK GEZIEN DOOR DE BEUGEL KUNNEN"',
  ],
  [
    "Karel",
    "Als een twaalfjarige zo agressief nee zegt is het duidelijk een ja",
  ],
  ["Karel", "Bloemen hebben de mooiste begravenis"],
  [
    "Karel",
    "Er zijn twee dingen waar ik heel hard op ga, symmetrie en over vrouwen urineren",
  ],
  ["Karel", 'Over Floris\' backref: "Je doet echt maar wat" ... "of niet?"'],
  ["Karel", "Ondanks dat we sociaal capabel zijn, stinken we nog steeds"],
  ["Karel", "Een boom hoeft geen consent te geven"],
  ["Karel", "Yes - groepsverkrachting!"],
  ["Karel", "Ik ben de Jezus van het Coronavirus"],
  [
    "Karel",
    "Voor €100,- per keer zou ik me gewoon laten uithoeren aan een 14 jarige.",
  ],
  [
    "Karel",
    "Dan had je maar niet zo'n laffe man moeten zijn, die zijn vrouw niet onder controle heeft",
  ],
  ["Karel", "Ik beloof dat ik je niet zal cucken, Jeffrey"],
  ["Karel", "Dan gaan Jeffrey en ik elkaar wel vingeren."],
  [
    "Karel",
    "Als je me eerst consent geeft en het dan weer intrekt had je maar niet zo'n tease moeten zijn.",
  ],
  ["Karel", "Shit. Weer ge-cockblocked door het partijkartel"],
  ["Karel", "Hhhhm, er gaat toch wel erg veel kinderporno door onze exitnode."],
  ["Karel", "Kom alsjeblieft je kinderporno bij mij hosten!"],
  ["Karel", "Ik weet vrij zeker dat ze geen 14 jaar is."],
  ["Karel", "Rectificatie: Jeffrey is toch niet zo'n schappelijke pimp."],
  ["Karel", "Jeffrey, er is geen ontkennen aan: Ik word nat van jou! 🍆💦"],
  ["Karel", "De enige droom die ik over mijn bruiloft heb, is de open bar"],
  ["Karel", "Hij heeft wel een punt: Huilende vrouwen kun je niet mee winnen"],
  [
    "Karel",
    "Ik dacht we maken er gewoon een leuke KKK meeting van; beetje kruizen verbranden enzo...",
  ],
  [
    "Karel",
    "Jeffrey wordt diegene die zwanger kan worden. Ik ga Jeffrey bezwangeren.",
  ],
  ["Karel", "Je kunt geen gesprek voeren terwijl je appelmoes eet."],
  ["Karel", "Deze zomer wordt net als 9/11, want de torens gaan neer"],
  ["Karel", "Joost gaat dan zichzelf maar melken"],
  [
    "Karel",
    "Ik snap wel dat je niet wil dat je zusje met Chad Thundercock in huis woont.",
  ],
  ["Karel", "Iiie, een donkere jongen! Paniek in mijn ogen."],
  [
    "Karel",
    "Dat heb je altijd met van de suicide dingen; liever een false-positive dan een false-negative.",
  ],
  ["Karel", "Ik weet niet of een kind makkelijker te nipple-twisten is."],
  ["Karel", "Wij zijn met 11MB/s felonies aan het plegen."],
  ["Karel", "Wij zijn zeer progressief met je knieschijven."],
  ["Karel", "Oh shit, ik heb een micropenis!"],
  ["Karel", "Ik krijg een stijve van Rutte "],
  ["Karel", "Gewoon wat ducttape over Jeffrey heen, niets aan het handje."],
  [
    "Karel",
    "Heleen mag mij wel tele-domineren. Dat is toch maar een kleine stap na fysiek domineren.",
  ],
  ["Karel", "Ik sta altijd klaar om dingen uit je anus te plukken."],
  [
    "Karel",
    "De Michelin man is ook wel erg geil. Ik wil dat hij me verstikt in zijn rolletjes.",
  ],
  ["Karel", "1,1 miljoen hoeren van een tientje, dat is de middenweg!"],
  ["Karel", "Ik wil gemanhandled worden met een fles Wodka"],
  ["Karel", "*snif snif* 😢 Nu weet ik het zeker, ik wil hem in me 💦"],
  ["Karel", "Sloeries worden getolereerd in de woonkamer."],
  ["Karel", "*zucht* Een vrouw met een mening vind ik al ver gaan."],
  [
    "Karel",
    "Ze kijkt helemaal niet onzeker. Kijk haar hoofd dan, ze is gebroken",
  ],
  ["Karel", "Morgen gun ik Noël de gaskamer"],
  [
    "Karel ",
    "Dat is waarom al die ouderen campers kopen, zodat ze dood kunnen gaan aan koolstofmonoxide.",
  ],
  ["Karel en Jeffey", "Tijd voor drugs? Ja natuurlijk!"],
  ["Karel, Floris", '"ja maar dan is het koud" -- "dat hoort bij de ervaring"'],
  [
    "Karel, Floris",
    '"hou hem nou in je broek, dat is wel zo beschaafd" - "dan stop je hem miet zomaar in je mond, maar is het een echte ervaring"',
  ],
  ["Karel, Floris", '"Lindsay heeft nóg grotere pp" - "I cry"'],
  ["Karel, Frank", '"En dan word je verkracht" - "Ja, dat is bijzaak"'],
  [
    "Karel, Joost",
    "Daarmee heb je zojuist groepsverkrachting gelegaliseerd... - Ja, dat was toch de bedoeling?",
  ],
  [
    "Karel, Lindsay",
    "Floris help, ik weet niet zo goed met hitsige Lindsay om te gaan - Nou je opties zijn vrij beperkt...",
  ],
  ["Karie", "Ik zit gewoon aan mijn eigen noten als ik aan jou denk 😘😏"],
  ["Karie de Poes", "Het heet galaplicht, geen galaconsent"],
  ["Minke", "Broertjes en zusjes kunnen dus met elkaar fucken"],
  ["Oliver", "Ik mag zelf kiezen welke goude ballen ik gebruik"],
  ["Oliver", "Met consent of niet het is sowieso fijn"],
  ["Oliver", "Je bent succesvoller als je dieper gaat."],
  ["Peter, Karel", "\"Daar hadden we ooit een rouwdienst\" 'Oh, leuk!'"],
  ["Suus", "Kunnen we bomen automatisch kapotmaken?"],
  [
    "Heleen",
    "*terwijl ze haar eigen hant fist* Ik kan dingen die Maarten niet kan 😏",
  ],
  ["Cato tegen stranger", "Maak me nat"],
  [
    "Darrell, Floris",
    "Alleen maar 18+ vanavond. Maar dat willen we helemaal niet ",
  ],
  ["Frank", "Huh?! Die van Jeffrey is groter! Die van mij is veel dunner."],
  ["max", "ik maak geen fouten, ik heb alleen leerzame ervaringen."],
  ["Jeffrey", "Na VB wil ik best om fietsen voor poes."],
  [
    "Karel",
    "Als je in een doos wilt komen, zal je er ook wel in moeten passen 💁‍♀️",
  ],
  ["Cato", "Nee, hij cumt!"],
  ["Max", "Bij een sleutel puntje moet ik meteen denken aan Leiden"],
  ["Cato, Darrell", "Ik geef geen consent. Huh, wat is dat?"],
  ["Joost", "Je moet nooit luisteren naar chick's, vooral als ze klein zijn "],
  ["Joost", "Waar staat de D voor?"],
  ["Minke, Max", "Je proeft de haartjes niet. Maar je voelt ze wel."],
  ["Jeffrey", "Voor wat ik doe, ben ik heel goedkoop"],
  ["Frank", "Consent is financieel onverantwoordelijk."],
  ["Max", "Ja, ik ga even een bak trekken"],
  ["Flip", "Mag ik je tiet zuigen?"],
  ["Cato", "Kom maar in mijn trein!"],
  ["Karel", "Als je maar blank genoeg bent, komt het altijd goed"],
  [
    "Minke, Darrell",
    "Ik denk dat mijn moeder de eerste keuze zou zijn om naakt mee te vechten. Als het alleen om de winst gaat ga ik voor een achtjarige.",
  ],
  [
    "Max, Minke",
    "Wat als we Squid Game voor hamsters doen? Maar zij hebben geen concept van geld. Maar wel van de dood!",
  ],
  ["Jeffrey, Karel", "Ondertussen is alle precum eraf gevallen. Helaas!"],
  ["Jeffrey", "We hebben meer witte rappers nodig!"],
  ["Joost", "Kom hier slet, we gaan PHP draaien"],
  ["Frank", "Hoofd is wel nice"],
  [
    "Jeffrey",
    "Ik hoef op het moment geen kinderen, maar dat zou ik wel overwegen als een grap.",
  ],
  ["Karel", "Bitches noemen mij de girth bender."],
  ["Max", "Straks raak ik je nog aan met m’n vieze stokje "],
  [
    "Oliver",
    'Ik zei dat ik geen consent gaf, en toen zei Cato "Nee, je vindt het wel leuk!"',
  ],
  ["Jeffrey", "Ho die ging er heel diep in"],
  ["Darrell", "Een beetje kanker, daar is nooit iemand dood aan gegaan toch"],
  [
    "Jeffrey naar Karel ",
    "Ik maak hem heet, en jij duwt hem in de plek die ik nat maak",
  ],
  ["Jeffrey", "Karel ben je klaar? Oke doe hem nu er in"],
  ["Jeffrey", "Jongens kijk eens hoe diep hij gaat"],
  ["Oliver", "Ik ga een 18-jarige aanduwen heeueeh"],
  ["Margot", "Ik ben racistisch, én …"],
  ["Max", "Ik ben racistisch, én …"],
  [
    "Ilse, Karel",
    "Jij wil niet baffen, of jij wilt niet gebaft worden? - Eigenlijk allebei wel",
  ],
  ["Cato", "Ik ben een klein, nutteloos meisje"],
  ["Minke", "Ik ben wel benieuwd naar zijn kont."],
  ["Minke", "Hij heeft ook schaamhaar enzo!"],
  ["Darrell", "Je bent niet hip als je geen kinderarbeid gebruikt "],
  [
    "Oliver, Jeffrey, Oliver, Cato",
    "We zijn echt heel erg geil. Wat hebben jullie gedaan? Cato heeft net een vrouw gemaakt. Gebaard!",
  ],
  ["Cato", "Je mag wel spoonen maar niet humpen"],
  ["Darrell, Max", "Vijf en driekwart. Prima leeftijd!"],
  ["Cato", "Ik ben een stoute poes"],
  ["Darrell, Max", "Heb je L&M tentamen gehaald? Ja! Wacht, gehaald... Nee."],
  ["Minke", "Gewoon een zetpil is best top!"],
  ["Minke", "Ze hebben niet eens seks dus wat is het punt?"],
  ["Cato", "Nee hotboxen in de Abscint is meer een SBZ ding"],
  ["Jeffrey", "Maar jij zei ook geen nee, dus iedereen is voor!"],
  [
    "Karel",
    '"Heb je zin in sexytime?" \'Nee\' "Sudo, hey heb je zin in sexy time?"',
  ],
  ["Max", "Kunnen we niet 5 losse pils bestellen en 1 droge pitcher?"],
  ["Jeffrey", "Ik heb daarnet ook al met Cato gebav’d"],
  ["Joost", "Je moet meer beffen"],
  [
    "Floris",
    "Waarom staat het water in de wc zo hoog in de Amerikas. Mn ballen moet ik optillen man",
  ],
  ["Jeffrey", "Fuck de fysieke wereld, letterlijk en figuurlijk!"],
  ["Minke", "Maar mijn moeder is gewoon heel erg seksueel"],
  ["Cato", "Zitten is het nieuwe staan"],
  ["Joost", "Dat vind ik geil"],
  ["Minke", "Ik verkracht alleen voor plezier."],
  [
    "Cato, Masha",
    "Welke kleur heeft het haar van de speler met de zandloper? Ginger.",
  ],
  ["Cato", "Ja meester ik gehoorzaam"],
  ["Minke", "Er zit gewoon al een condoom om, for her pleasure!"],
  [
    "Minke, Cato",
    "Ik zeg altijd 30 centimeter kloppend vlees. Wat? Over mijn penis.",
  ],
  ["Minke", "Hey Oliver; sweet ass!"],
  ["Cato", "Ik ben heel goed in doen alsof ik een hoer ben "],
  ["Darrell", "Tussen 30 en 50 is geen verschil joh"],
  ["Karel", "En sommige van ons zijn homo Homo Sapiens, en dat is oké."],
  ["Joost", "Oh ja, ik vergeet altijd dat black lives matter"],
  [
    "Darrell",
    "Als ik een kind neem dan wordt het adoptie, maar geen Chinees, want dat is lullig.",
  ],
  [
    'Joost "onze penningmeester"',
    "Er is een structureel probleem met declaraties van bestuur die onterecht goedgekeurd worden",
  ],
  ["Darrell", "Eerst was Suus makkelijk, maar toen kwam Max"],
  ["Cato", "Ching chong!"],
  ["Max", "We love wit!"],
  ["Oliver", "Een kontgat kan je niet terug draaien"],
  ["Max", "Ik heb een halve luier om"],
  ["Darrell", "Jongens kan ik alsjeblieft 1 avond niet aangerand worden?"],
];
